import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { X, GitBranch, ChevronDown, ShieldCheck, ArrowRight } from 'lucide-react';
import { actions, useUiStore, useNowcastStore } from '../store';
import useNowcast from '../features/useNowcast';
import { Badge, number, time, Metric, eta } from './common';
import ScenarioControls from './ScenarioControls';
import AlertLedger from './AlertLedger';
import useAlerts, { prioritizeAlerts } from '../features/useAlerts';
import { isOpenAlert } from '../lib/alerts';
import useMotionPreference from '../features/useMotionPreference';
export default function InspectionDrawer() {
  const inspection = useUiStore(state => state.inspection);
  const snapshot = useNowcast();
  const observed = useNowcastStore(state => state.observedSnapshot);
  const records = useAlerts();
  const [traceView, setTraceView] = useState('latest');
  const ref = useRef<HTMLElement>(null);
  const reduced = useMotionPreference();
  useEffect(() => { setTraceView('latest'); }, [inspection?.id]);
  useEffect(() => {
    if (!inspection) return;
    const previous = document.activeElement as HTMLElement | null;
    const timer = setTimeout(() => ref.current?.querySelector<HTMLButtonElement>('button')?.focus(),30);
    const listener = (event: KeyboardEvent) => {
      if (event.key === 'Escape') actions.close();
      if (event.key === 'Tab') {
        const elements = ref.current?.querySelectorAll<HTMLElement>('button, input, select, summary, [tabindex="0"]');
        if (!elements?.length) return;
        const first = elements[0], last = elements[elements.length-1];
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
        if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
      }
    };
    document.addEventListener('keydown',listener);
    return () => { clearTimeout(timer); document.removeEventListener('keydown',listener); previous?.focus(); };
  }, [inspection]);
  const source = observed.sources.find(item => item.name === inspection?.id);
  const hazard = snapshot.hazards.find(item => item.type === inspection?.id);
  const alert = records.find(item => item.alertId === inspection?.id) ?? prioritizeAlerts(records)[0];
  const selectedStorm = inspection?.kind === 'storm' ? snapshot.stormCells?.find(item => item.id === inspection.id) ?? snapshot.storm : snapshot.storm;
  const title = inspection?.kind === 'alerts' ? 'ADVISORY JOURNAL' : inspection?.kind === 'alert' ? 'TRACE THIS ALERT' : inspection?.kind === 'source' ? 'SOURCE PROVENANCE' : inspection?.kind === 'fusion' ? 'WHY CONVECTION?' : inspection?.kind === 'hazard' ? `${inspection.id.toUpperCase()} EVIDENCE` : inspection?.kind === 'controls' ? 'SCENARIO INTERVENTION' : inspection?.kind === 'pipeline' ? 'PROCESSING INSPECTION' : inspection?.kind === 'location' ? 'CONTEXTUAL LOCATION' : 'STORM INTELLIGENCE';
  return <AnimatePresence>{inspection && <><motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={actions.close}/><motion.aside ref={ref} className="inspection-drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title" initial={{x:reduced ? 0 : 480}} animate={{x:0}} exit={{x:reduced ? 0 : 480}} transition={{duration:0.22}}><header><div><span className="eyebrow">EVIDENCE / INSPECTION</span><h2 id="drawer-title">{title}</h2></div><button className="icon-button" aria-label="Close inspection" onClick={actions.close}><X size={20}/></button></header><div className="drawer-context"><Badge tone="amber">SYNTHETIC</Badge><span>{snapshot.scenarioId} · {time(snapshot.timestamp)} IST</span></div><div className="drawer-body">
    {inspection.kind === 'controls' && <ScenarioControls/>}
    {inspection.kind === 'alerts' && <AlertLedger compact/>}
    {source && inspection.kind === 'source' && <><h3>{source.name}</h3><p>Locally generated scenario frame. No DWR, INSAT or official lightning feed is connected.</p><div className="detail-table">{[['Frame ID',source.frameId],['Observation time',`${time(source.timestamp)} IST`],['Provenance','Synthetic / local replay'],['Quality state',source.quality.state],['Coverage',`${number(source.quality.coverage)}%`],['Completeness',`${number(source.quality.completeness)}%`],['Temporal alignment','Aligned synthetic clock'],['Spatial alignment','Shared schematic domain'],['Delivery latency','Not applicable · local frame'],['Feature extraction',source.quality.score > 0 ? 'Computed locally' : 'Source unavailable']].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{source.metrics.map(metric => <Metric key={metric.label} label={metric.label} value={number(metric.value,1)} unit={metric.unit}/>)}</>}
    {inspection.kind === 'fusion' && <><h3>Corroboration, not an “AI score”</h3><p>The prototype fuses three normalized synthetic signals using quality-adjusted scenario weights. These weights and indices are not scientifically calibrated.</p>{snapshot.evidence.map((item,index) => <div className="evidence-card" key={item.source}><span className="eyebrow">{item.source} / FEATURE {index+1}</span><h4>{item.feature}</h4><strong>{number(item.value,1)} {item.unit}</strong><p>{item.derivation}</p><small>Frame {item.frameId} · quality {item.quality}%</small></div>)}<div className="formula">wᵢ = base_weightᵢ × qualityᵢ / Σ(weight × quality)<br/>signal = Σ(wᵢ × normalized_signalᵢ) × (1 − noise/200)<br/>agreement = 100 − signal spread − noise<br/>confidence = quality × (0.35 + 0.0065 × agreement) × horizon decay</div><div className="drawer-metrics"><Metric label="FUSED SIGNAL" value={number(snapshot.fusion.signal)} unit="/100"/><Metric label="AGREEMENT" value={number(snapshot.fusion.agreement)} unit="%"/><Metric label="CONFIDENCE" value={number(snapshot.fusion.confidence)} unit="%"/></div><p className="amber-text">{snapshot.fusion.agreement < 65 ? 'Source disagreement detected. Confidence reduced; review required.' : 'Inputs corroborate this scenario signal. This is not real-world forecast validation.'}</p><h3>Initiation classification</h3><p>Signal gates: watch &gt;17, initiating &gt;32, active &gt;48, severe &gt;74. After T+185, the primary scenario dissipates.</p></>}
    {inspection.kind === 'alert' && (alert ? <><h3>{alert.hazardType.toUpperCase()} · {alert.alertId}</h3><Badge tone={alert.status === 'ACKNOWLEDGED' || alert.status === 'RESOLVED' ? 'green' : 'amber'}>{alert.status}</Badge><p className="trace-disclaimer">Retained scenario advisory. Operator acknowledgment records review only; this is not an official warning.</p><div className="detail-table"><div><span>Generated</span><strong>{time(alert.timestamp)} IST</strong></div><div><span>Last updated</span><strong>{time(alert.lastUpdated)} IST</strong></div><div><span>Latest risk / confidence</span><strong>{number(alert.risk)}/100 · {number(alert.confidence)}%</strong></div></div><div className="segmented-control trace-switch"><button className={traceView === 'latest' ? 'active' : ''} onClick={() => setTraceView('latest')}>Latest qualifying evidence</button><button className={traceView === 'origin' ? 'active' : ''} onClick={() => setTraceView('origin')}>Generation evidence</button></div><p className="trace-disclaimer">{traceView === 'origin' ? 'Frozen evidence from the first generated / received advisory.' : 'Latest evidence that qualified this advisory. Expired records retain their last qualifying trace; expiration is explained in the audit.'}</p><div className="trace-flow">{(traceView === 'origin' ? alert.originTrace : alert.trace).map((stage,index) => <details key={`${traceView}-${stage.stage}`} open={index === 0 || index === 6}><summary><GitBranch size={15}/>{stage.stage}<ChevronDown size={14}/></summary><p>{stage.detail}</p></details>)}</div><button className="primary-button" disabled={!isOpenAlert(alert.status) || alert.status === 'ACKNOWLEDGED' || snapshot.mode === 'BACKEND'} onClick={() => actions.acknowledge(alert.alertId)}><ShieldCheck size={15}/>{alert.status === 'ACKNOWLEDGED' ? 'Acknowledged' : 'Acknowledge advisory'}</button><button className="subtle-button" disabled={!isOpenAlert(alert.status) || snapshot.mode === 'BACKEND'} onClick={() => actions.acknowledge(alert.alertId,true)}>Resolve in demo</button><h3>Alert lifecycle audit</h3>{alert.audit.map((item,index) => <div className="audit-row" key={index}><span>{time(item.time)} IST</span>{item.action}</div>)}<button className="text-button" onClick={() => actions.inspect('alerts')}>Back to advisory journal<ArrowRight size={13}/></button></> : <p>No retained alert at this replay instant. Low risk or confidence can intentionally suppress advisories.</p>)}
    {inspection.kind === 'hazard' && hazard && <><h3>{hazard.type} illustrative risk</h3><div className="drawer-metrics"><Metric label="RISK INDEX" value={number(hazard.risk)} unit="/100"/><Metric label="HEURISTIC CONFIDENCE" value={number(hazard.confidence)} unit="%"/></div><Badge tone={hazard.severity === 'REVIEW' ? 'amber' : 'red'}>{hazard.severity}</Badge><p>Not a calibrated probability. No official forecast or validated downburst velocity / rainfall estimate is asserted.</p>{hazard.evidence.map(item => <div className="evidence-card" key={item.feature}><span>{item.source}</span><h4>{item.feature}</h4><strong>{number(item.value,1)} {item.unit}</strong><small>Quality {item.quality}% · {item.frameId}</small></div>)}<button className="primary-button" onClick={() => actions.inspect('fusion')}>Inspect feature → fusion lineage<ArrowRight size={15}/></button><div className="detail-table">{hazard.forecast.map(point => <div key={point.minute}><span>+{point.minute} min</span><strong>{number(point.risk)} /100 · confidence {number(point.confidence)}%</strong></div>)}</div></>}
    {inspection.kind === 'storm' && <><h3>{selectedStorm.id} / {selectedStorm.state}</h3><p>This detected cell has explicit motion, bounded indices and horizon-dependent uncertainty.</p><div className="drawer-metrics"><Metric label="SPEED" value={selectedStorm.speed} unit="km/h"/><Metric label="ETA" value={eta(selectedStorm.eta)}/><Metric label="AREA" value={number(selectedStorm.area)} unit="km²"/></div><div className="detail-table">{selectedStorm.trajectory.map(point => <div key={point.leadMinutes}><span>+{point.leadMinutes} min</span><strong>{number(point.latitude,3)}° N / {number(point.longitude,3)}° E ±{number(point.uncertaintyKm,1)} km</strong></div>)}</div><p>Observed and forecast paths use separate solid / dashed encodings. The corridor grows with lead time and reduced source confidence.</p><button className="primary-button" onClick={actions.focus}>Focus cell on map</button><button className="subtle-button" onClick={() => actions.inspect('controls')}>Change storm conditions</button></>}
    {inspection.kind === 'pipeline' && <><h3>{inspection.id}</h3><p>The local heuristic engine computes the full snapshot synchronously. Stage names expose conceptual processing boundaries; they are not separate operational Python services.</p><div className="detail-table"><div><span>Engine</span><strong>{snapshot.engineVersion}</strong></div><div><span>Input records</span><strong>{snapshot.evidence.filter(item => item.quality > 0).length}</strong></div><div><span>Measured total computation</span><strong>{number(snapshot.performance.computationMs,3)} ms</strong></div><div><span>Per-stage latency</span><strong>Not instrumented</strong></div></div><p>Timestamp normalization and spatial alignment are guaranteed by the synthetic generator. Real-source alignment, radar filtering and segmentation remain future backend work.</p></>}
    {inspection.kind === 'location' && <><h3>{inspection.id}</h3><p>Approximate contextual demo location. Not an authoritative infrastructure dataset.</p><Metric label="CELL TO CENTRAL PUNE" value={number(snapshot.storm.distance,1)} unit="km"/><p>Population exposure, asset-specific ETA and authoritative asset inventories are not available in this prototype.</p></>}
    <div className="drawer-footnote">MODEL / {snapshot.engineVersion}<br/>SCHEMA / {snapshot.schemaVersion}<br/>SIMULATED OBSERVATIONS · UNVALIDATED HEURISTICS</div>
  </div></motion.aside></>}</AnimatePresence>;
}
