import { Radar, Satellite, Zap, ArrowUpRight, Activity, ShieldCheck, ArrowRight, TriangleAlert, Wind, CloudRain, Hexagon, GitBranch, CircleCheck, ChevronRight } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import useNowcast from '../features/useNowcast';
import { actions, useNowcastStore, useScenarioStore } from '../store';
import useAlerts, { prioritizeAlerts } from '../features/useAlerts';
import { isOpenAlert } from '../lib/alerts';
import { Badge, Metric, Panel, InspectButton, number, eta, time, Info } from './common';
export function Sources() {
  const snapshot = useNowcastStore(state => state.observedSnapshot);
  const icons = [Radar, Satellite, Zap];
  return <div className="source-stack"><div className="column-heading"><span>01</span><h2>MULTI-SOURCE INGESTION</h2><span className="tiny-live">LOCAL</span></div>{snapshot.sources.map((source,index) => { const Icon = icons[index]; return <section className={`source-panel source-${index}`} key={source.name}><header><div className="source-name"><Icon size={18}/><h3>{source.name}</h3></div><Badge tone={source.quality.state === 'GOOD' ? 'green' : source.quality.state === 'FAILED' ? 'red' : 'amber'}>{source.quality.state === 'GOOD' ? 'READY' : source.quality.state}</Badge></header><div className="source-primary"><strong>{number(source.metrics[0].value, index === 1 ? 1 : 0)}</strong><span>{source.metrics[0].unit}</span><span className="signal-trend"><ArrowUpRight size={13}/>{number(source.signal)} signal</span></div><span className="source-primary-label">{source.metrics[0].label}</span><div className="source-metrics">{source.metrics.slice(1).map(metric => <div key={metric.label}><span>{metric.label}</span><strong>{number(metric.value,1)} <small>{metric.unit}</small></strong></div>)}</div><footer><span className="mono">{time(source.timestamp)} IST</span><button onClick={() => actions.inspect('source',source.name)}>Frame provenance <ChevronRight size={12}/></button></footer></section>; })}
    <Panel title="DATA QUALITY GATE" action={<ShieldCheck size={14} className="green-text"/>} className="quality-panel">{snapshot.sources.map(source => <button className="quality-row" key={source.name} onClick={() => actions.inspect('source',source.name)}><span>{source.name.split(' ')[0]}</span><div className="progress-track"><div className={source.quality.state === 'GOOD' ? 'green-bg' : 'amber-bg'} style={{ width:`${source.quality.score}%` }}/></div><strong>{number(source.quality.score)}%</strong></button>)}<div className="quality-caption">{snapshot.fusion.quality < 70 ? 'DEGRADED INPUTS · CONFIDENCE REDUCED' : 'SYNTHETIC FRAMES · TIME-ALIGNED'}</div></Panel>
  </div>;
}
export function Fusion() {
  const snapshot = useNowcast();
  return <Panel title="MULTI-SOURCE FUSION" action={<InspectButton onClick={() => actions.inspect('fusion')}>Explain</InspectButton>} className="fusion-panel"><div className="fusion-flow">{['DWR','INSAT','LGT'].map((name,index) => <div key={name}><span>{name}</span><strong>{number(snapshot.sources[index].contribution)}<small>%</small></strong><div className="progress-track"><div style={{ width:`${snapshot.sources[index].contribution}%` }}/></div></div>)}<ArrowRight size={16}/><div className="fusion-result"><span>FUSED SIGNAL</span><strong>{number(snapshot.fusion.signal)}<small>/100</small></strong></div></div><div className="fusion-footer"><span>Source agreement <strong className={snapshot.fusion.agreement < 65 ? 'amber-text' : 'cyan-text'}>{number(snapshot.fusion.agreement)}%</strong></span><span>Confidence <strong>{number(snapshot.fusion.confidence)}%</strong></span></div><small className="muted">Scenario contributions · uncalibrated heuristic</small></Panel>;
}
export function Threat() {
  const snapshot = useNowcast();
  const threshold = useScenarioStore(state => state.parameters.confidenceThreshold);
  const highest = [...snapshot.hazards].sort((first,second) => second.risk-first.risk)[0];
  return <div className="threat-stack"><section className="threat-panel"><div className="threat-heading"><TriangleAlert size={16}/><span>{snapshot.lead > 0 ? 'PROJECTED THREAT' : 'CURRENT THREAT'}</span><span className="threat-level">{highest.severity}</span></div><h2>{snapshot.storm.state === 'DISSIPATING' ? 'CONVECTION\nWEAKENING' : snapshot.storm.state === 'NORMAL' ? 'NO SIGNIFICANT\nCONVECTION' : 'CONVECTIVE\nACTIVITY DETECTED'}</h2><div className="threat-cell"><span>{snapshot.storm.id}</span><Badge tone="amber">{snapshot.storm.state}</Badge></div><div className="threat-hazards">{snapshot.hazards.filter(hazard => hazard.risk > 40).map(hazard => <span key={hazard.type}>{hazard.type.toUpperCase()}</span>)}</div><div className="eta-heading"><span>IMPACT ETA · CENTRAL PUNE</span><Info text="Linear closest-approach estimate from synthetic cell position, bearing, speed and a 12 km target corridor. Not an operational arrival prediction."/></div><div className="eta-number">{eta(snapshot.storm.eta)}<span>MIN : SEC</span></div><div className="eta-context"><span>{number(snapshot.storm.distance,1)} km to target</span><span>{snapshot.storm.speed} km/h ↗</span></div><footer><span>{snapshot.fusion.confidence < threshold ? 'INSUFFICIENT EVIDENCE' : 'MODEL CONFIDENCE'}</span><strong>{number(snapshot.fusion.confidence)}%</strong></footer></section>
    <Panel title="STORM INTELLIGENCE" action={<InspectButton onClick={() => actions.inspect('storm')}/> }><div className="storm-metric-grid"><Metric label="REFLECTIVITY" value={number(snapshot.storm.intensity,1)} unit="dBZ"/><Metric label="CELL AREA" value={number(snapshot.storm.area)} unit="km²"/><Metric label="GROWTH RATE" value={`${snapshot.storm.growth >= 0 ? '+' : ''}${number(snapshot.storm.growth)}`} unit="%/15m" tone="cyan-text"/><Metric label="BEARING" value={number(snapshot.storm.direction)} unit="° ENE"/></div><button className="lineage-link" onClick={() => actions.inspect('fusion')}><GitBranch size={14}/>Why was convection detected?<ChevronRight size={14}/></button></Panel>
    <Panel title="HAZARD INTELLIGENCE" action={<span className="eyebrow">INDEX /100</span>} className="hazards-panel">{snapshot.hazards.map((hazard,index) => { const Icon = [Zap,Hexagon,Wind,CloudRain][index]; return <button className="hazard-row" key={hazard.type} onClick={() => actions.inspect('hazard',hazard.type)}><Icon size={15}/><span>{hazard.type}</span><div className="hazard-bar"><div style={{ width:`${hazard.risk}%` }}/></div><strong>{number(hazard.risk)}</strong><ChevronRight size={12}/></button>; })}<small className="muted">Illustrative risk indices, not calibrated probabilities.</small></Panel></div>;
}
export function Pipeline() {
  const snapshot = useNowcast();
  return <section className="pipeline"><div className="pipeline-label"><Activity size={16}/><span>PROCESSING<br/><strong>PIPELINE</strong></span></div><div className="pipeline-stages">{snapshot.performance.stages.map((stage,index) => <button key={stage.name} onClick={() => actions.inspect('pipeline',stage.name)}><span className={`stage-dot ${stage.status === 'READY' ? '' : 'degraded'}`}><CircleCheck size={12}/></span><span>{stage.name}</span>{index < snapshot.performance.stages.length-1 && <ChevronRight className="stage-arrow" size={12}/>}</button>)}</div><div className="pipeline-end"><strong>{number(snapshot.performance.computationMs,2)}<small>ms</small></strong><span>LOCAL COMPUTE</span></div></section>;
}
export function EvolutionChart({ height = 160 }: { height?: number }) {
  const snapshot = useNowcast();
  const points = snapshot.hazards[0].forecast.map(point => ({ minute: point.minute, risk: point.risk, confidence: point.confidence }));
  return <div style={{ height }} className="chart-container"><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{ top:10,right:5,left:-25,bottom:0 }}><defs><linearGradient id="riskFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#42c8c4" stopOpacity={0.25}/><stop offset="100%" stopColor="#42c8c4" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#263541" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="minute" tickFormatter={value => value === 0 ? 'NOW' : `+${value}m`} stroke="#718797" tickLine={false} axisLine={false} tick={{fontSize:10}}/><YAxis domain={[0,100]} stroke="#718797" tickLine={false} axisLine={false} tick={{fontSize:10}}/><Tooltip contentStyle={{background:'#101b27',border:'1px solid #344953',fontSize:12}} formatter={(value,name) => [`${Number(value).toFixed(1)} ${name === 'risk' ? '/100' : '%'}`,name === 'risk' ? 'Lightning risk index' : 'Heuristic confidence']}/><Area dataKey="risk" stroke="#42c8c4" strokeWidth={2} fill="url(#riskFill)"/><Area dataKey="confidence" stroke="#758ca5" strokeDasharray="4 3" fill="none"/></AreaChart></ResponsiveContainer></div>;
}
export function AlertCenter() {
  const records = useAlerts();
  const mode = useNowcastStore(state => state.snapshot.mode);
  const open = prioritizeAlerts(records.filter(record => isOpenAlert(record.status)));
  const alert = open[0];
  return <Panel title="ALERT & DECISION LOG" action={<button className="text-button" onClick={() => actions.inspect('alerts')}>{open.length} OPEN · JOURNAL<ChevronRight size={12}/></button>} className="alert-panel">{alert ? <><div className="alert-summary"><span className="alert-icon"><TriangleAlert size={18}/></span><div><strong>{alert.hazardType.toUpperCase()} RISK · {alert.stormCellId}</strong><span>Central Pune corridor · {alert.severity} · {number(alert.confidence)}% confidence</span></div><Badge tone={alert.status === 'ACKNOWLEDGED' ? 'green' : alert.status === 'ESCALATED' ? 'red' : 'amber'}>{alert.status === 'ACTIVE' ? 'REVIEW' : alert.status}</Badge></div><div className="alert-actions"><button onClick={() => actions.inspect('alert',alert.alertId)}><GitBranch size={13}/>Trace this alert<ArrowRight size={13}/></button><button onClick={() => actions.acknowledge(alert.alertId)} disabled={alert.status === 'ACKNOWLEDGED' || mode === 'BACKEND'}><ShieldCheck size={13}/>{alert.status === 'ACKNOWLEDGED' ? 'Acknowledged' : 'Acknowledge'}</button></div><small className="muted">Current observations only · {records.length} retained advisories · not an official warning</small></> : <div className="empty-state"><ShieldCheck size={22}/><strong>No actionable advisories</strong><span>Below risk threshold or insufficient corroborating evidence. {records.length} retained journal records.</span><InspectButton onClick={() => actions.inspect('alerts')}>Inspect retained journal</InspectButton></div>}</Panel>;
}
