import { Play, Pause, RotateCcw, SkipForward, SkipBack, Clock3 } from 'lucide-react';
import { actions, useScenarioStore, useNowcastStore } from '../store';
import { time } from './common';
export default function ReplayControl() {
  const { minute, playing, speed, scenarioId, scenarios, mode } = useScenarioStore();
  const snapshot = useNowcastStore(state => state.snapshot);
  return <section className="replay-control" aria-label="Scenario replay controls"><div className="replay-top"><div className="replay-name"><Clock3 size={15}/><span>SCENARIO REPLAY</span><select aria-label="Select scenario" value={scenarioId} onChange={event => actions.selectScenario(event.target.value)}>{scenarios.map(scenario => <option key={scenario.id} value={scenario.id}>{scenario.id} · {scenario.name}</option>)}</select></div><div className="replay-time"><span>SIMULATION TIME</span><strong>{time(snapshot.timestamp)} <small>IST</small></strong><span className="cyan-text">T+{Math.floor(minute).toString().padStart(3,'0')} MIN</span></div></div><div className="replay-bottom"><div className="playback-buttons"><button aria-label="Previous replay event" title="Previous event" disabled={mode === 'BACKEND'} onClick={() => actions.seek(Math.max(0,minute-15))}><SkipBack size={15}/></button><button className="play-button" title="Play or pause (Space)" aria-label={playing ? 'Pause replay' : 'Play replay'} disabled={mode === 'BACKEND'} onClick={actions.play}>{playing ? <Pause size={16}/> : <Play size={16} fill="currentColor"/>}</button><button aria-label="Next replay event" title="Next event (N)" disabled={mode === 'BACKEND'} onClick={actions.next}><SkipForward size={15}/></button><button aria-label="Reset scenario" title="Reset scenario (R)" onClick={actions.reset}><RotateCcw size={14}/></button><select aria-label="Playback speed" value={speed} onChange={event => useScenarioStore.setState({ speed:Number(event.target.value) })}>{[0.5,1,2,4].map(value => <option key={value} value={value}>{value}×</option>)}</select></div><div className="replay-slider"><input type="range" min="0" max="240" step="1" value={minute} disabled={mode === 'BACKEND'} aria-label="Replay elapsed minutes" onChange={event => actions.seek(Number(event.target.value))}/><div className="timeline-labels">{[[0,'NORMAL'],[20,'INITIATION'],[60,'SEVERE'],[120,'INTENSIFYING'],[180,'PEAK'],[240,'DISSIPATION']].map(([value,label]) => <button key={value} onClick={() => actions.seek(Number(value))}><span>T+{value}</span>{label}</button>)}</div></div></div></section>;
}
export function ForecastTimeline() {
  const lead = useScenarioStore(state => state.lead);
  return <div className="forecast-timeline"><span>NOWCAST<br/><strong>HORIZON</strong></span>{[0,15,30,60,120,180,240,300,360].map(value => <button key={value} onClick={() => actions.setLead(value)} className={lead === value ? 'active' : ''} aria-pressed={lead === value}>{value === 0 ? 'NOW' : value < 60 ? `+${value}M` : `+${value/60}H`}</button>)}<span className="forecast-label">{lead === 0 ? 'CURRENT SCENARIO' : 'ILLUSTRATIVE FORECAST'}</span></div>;
}
